In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("bnpl_dataset.csv")

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (50000, 9)

,Transaction_ID,Customer_Age,Gender,Annual_Income,Credit_Score,Purchase_Category,BNPL_Provider,Purchase_Amount,Repayment_Status
0,6cbfd4e5-8e91-4a7b-8a14-e3dfa86a3359,56,Male,32293,353,Beauty,Sezzle,249,Defaulted
1,863e8aa6-847e-4ae0-b96b-65241f3450a2,46,Male,72774,354,Groceries,Affirm,188,Paid On Time
2,a24efee2-16f2-42dc-a0e7-6df4960df0b8,32,Male,82207,630,Travel,Sezzle,1610,Paid On Time
3,bbad847a-a92f-4766-ba3f-98b9b199b4cf,60,Male,92498,470,Fashion,Sezzle,120,Paid On Time
4,3f1b1928-09ca-4d06-8ec3-4efd3468d0ec,25,Male,32060,502,Travel,Klarna,1849,Paid On Time

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Transaction_ID     50000 non-null  str
 1   Customer_Age       50000 non-null  int64
 2   Gender             50000 non-null  str
 3   Annual_Income      50000 non-null  int64
 4   Credit_Score       50000 non-null  int64
 5   Purchase_Category  50000 non-null  str
 6   BNPL_Provider      50000 non-null  str
 7   Purchase_Amount    50000 non-null  int64
 8   Repayment_Status   50000 non-null  str
dtypes: int64(4), str(5)
memory usage: 3.4 MB

In [4]:
missing_values = df.isnull().sum()
missing_percentage = (df.isnull().sum() / len(df)) * 100

print("Missing Values:")
print(missing_values)

print("\nMissing Percentage:")
print(missing_percentage)

Missing Values:
Transaction_ID       0
Customer_Age         0
Gender               0
Annual_Income        0
Credit_Score         0
Purchase_Category    0
BNPL_Provider        0
Purchase_Amount      0
Repayment_Status     0
dtype: int64

Missing Percentage:
Transaction_ID       0.0
Customer_Age         0.0
Gender               0.0
Annual_Income        0.0
Credit_Score         0.0
Purchase_Category    0.0
BNPL_Provider        0.0
Purchase_Amount      0.0
Repayment_Status     0.0
dtype: float64

In [5]:
duplicates = df.duplicated().sum()
print("Number of Duplicate Rows:", duplicates)

Number of Duplicate Rows: 0

In [6]:
df.describe()

       Customer_Age  Annual_Income  Credit_Score  Purchase_Amount
count  50000.000000   50000.000000  50000.000000     50000.000000
mean      40.979240   69980.860200    573.569300       563.221980
std       13.528733   28923.444012    158.853766       706.078491
min       18.000000   20000.000000    300.000000        20.000000
25%       29.000000   44915.500000    435.000000       124.000000
50%       41.000000   70071.500000    572.000000       229.000000
75%       53.000000   95262.250000    711.000000       785.000000
max       64.000000  119998.000000    849.000000      2999.000000

In [7]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

df[num_cols] = df[num_cols].fillna(df[num_cols].median())

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

print("Missing values after treatment:")
print(df.isnull().sum())

Missing values after treatment:
Transaction_ID       0
Customer_Age         0
Gender               0
Annual_Income        0
Credit_Score         0
Purchase_Category    0
BNPL_Provider        0
Purchase_Amount      0
Repayment_Status     0
dtype: int64

C:\Users\mohal\AppData\Local\Temp\ipykernel_10448\2935805157.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include=['object']).columns

In [8]:
print("Duplicates Before:", df.duplicated().sum())
df.drop_duplicates(inplace=True)
print("Duplicates After:", df.duplicated().sum())

Duplicates Before: 0
Duplicates After: 0

In [9]:
for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    df[col] = np.where(df[col] < lower_bound, lower_bound, df[col])
    df[col] = np.where(df[col] > upper_bound, upper_bound, df[col])

print("Outliers treated using IQR method.")

Outliers treated using IQR method.

In [10]:
df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

print("Categorical variables encoded successfully.")

Categorical variables encoded successfully.

In [11]:
scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

print("Feature scaling completed.")

Feature scaling completed.

In [12]:
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Columns: 50015 entries, Customer_Age to Repayment_Status_Paid On Time
dtypes: bool(50011), float64(4)
memory usage: 2.3 GB

,Customer_Age,Annual_Income,Credit_Score,Purchase_Amount,Transaction_ID_0000fe21-2c64-4007-b050-66f494168d9b,Transaction_ID_00042bcc-1fe3-4695-bf1b-0e83bdfc02f7,Transaction_ID_00047296-c543-4ca3-a13c-c35ad133d707,Transaction_ID_0004ce18-1b90-4ef2-8f04-8410c930ff45,Transaction_ID_0006250d-d483-44b2-94dc-265b50b08a7a,Transaction_ID_00085fe1-8dc8-4a72-87ff-d4641d44daac,...,Purchase_Category_Electronics,Purchase_Category_Fashion,Purchase_Category_Groceries,Purchase_Category_Home & Furniture,Purchase_Category_Travel,BNPL_Provider_Afterpay,BNPL_Provider_Klarna,BNPL_Provider_Sezzle,Repayment_Status_Late Payment,Repayment_Status_Paid On Time
0,1.110297,-1.303034,-1.388519,-0.454522,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,0.371122,0.096571,-1.382224,-0.558370,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,True
2,-0.663723,0.422711,0.355240,1.862479,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,True
3,1.405967,0.778516,-0.651985,-0.674135,False,False,False,False,False,False,...,False,True,False,False,False,False,False,True,False,True
4,-1.181145,-1.311090,-0.450540,2.145933,False,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,True